import{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import Papa from"papaparse";import"./styles.css";
type ApiResult={status:number;statusText:string;duration:number;headers:Record<string,string>;body:string}|null;
type Row=Record<string,unknown>;
const sample=JSON.stringify({message:"Hello world",ok:true,items:[1,2,3]},null,2);
function App(){const[tool,setTool]=useState<"api"|"csv"|"json">("api");const[url,setUrl]=useState("https://jsonplaceholder.typicode.com/todos/1");const[method,setMethod]=useState("GET");const[requestBody,setRequestBody]=useState("");const[apiResult,setApiResult]=useState<ApiResult>(null);const[apiError,setApiError]=useState("");const[loading,setLoading]=useState(false);const[json,setJson]=useState(sample);const[jsonError,setJsonError]=useState("");const[rows,setRows]=useState<Row[]>([]);const[columns,setColumns]=useState<string[]>([]);const[csvName,setCsvName]=useState("");const[csvError,setCsvError]=useState("");const[query,setQuery]=useState("");
const filtered=useMemo(()=>{if(!query.trim())return rows;const q=query.toLowerCase();return rows.filter(r=>Object.values(r).some(v=>String(v??"").toLowerCase().includes(q)))},[rows,query]);
async function send(){setLoading(true);setApiError("");setApiResult(null);const start=performance.now();try{const r=await fetch(url,{method,headers:{"Content-Type":"application/json","Accept":"application/json,text/plain,*/*"},body:["GET","HEAD"].includes(method)?undefined:(requestBody||undefined)});const text=await r.text();const headers:Record<string,string>={};r.headers.forEach((v,k)=>headers[k]=v);setApiResult({status:r.status,statusText:r.statusText,duration:Math.round(performance.now()-start),headers,body:text})}catch(e){setApiError(e instanceof Error?e.message:"Request failed. Many APIs block browser requests with CORS; use a server-side monitor for those endpoints.")}finally{setLoading(false)}}
function format(){try{setJson(JSON.stringify(JSON.parse(json),null,2));setJsonError("")}catch(e){setJsonError(e instanceof Error?e.message:"Invalid JSON")}}
function csvFile(file:File){setCsvName(file.name);setCsvError("");Papa.parse<Row>(file,{header:true,skipEmptyLines:true,complete:r=>{setRows(r.data);setColumns(r.meta.fields??[]);},error:e=>setCsvError(e.message)})}
function downloadCsv(){const blob=new Blob([Papa.unparse(rows)],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="cleaned-data.csv";a.click();URL.revokeObjectURL(a.href)}
return <div className="shell"><header><a className="logo" href="#"><span className="mark">⚡</span> API CSV Tools</a><nav><button className={tool==="api"?"nav active":"nav"} onClick={()=>setTool("api")}>API Tester</button><button className={tool==="csv"?"nav active":"nav"} onClick={()=>setTool("csv")}>CSV Tools</button><button className={tool==="json"?"nav active":"nav"} onClick={()=>setTool("json")}>JSON</button></nav><a className="github" href="https://github.com/shalubano637-ship-it/api-csv-tools" target="_blank">GitHub ↗</a></header>
<main><section className="hero"><div className="pill">FREE DEVELOPER TOOLKIT</div><h1>Work with APIs and data<br/><em>without the busywork.</em></h1><p>Test HTTP endpoints, format JSON and inspect CSV files instantly. Your CSV stays in your browser.</p></section>
<section className="toolcard"><div className="tabs"><button className={tool==="api"?"selected":""}onClick={()=>setTool("api")}>API request</button><button className={tool==="csv"?"selected":""}onClick={()=>setTool("csv")}>CSV viewer</button><button className={tool==="json"?"selected":""}onClick={()=>setTool("json")}>JSON formatter</button></div>
{tool==="api"&&<><div className="request"><select value={method}onChange={e=>setMethod(e.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input value={url}onChange={e=>setUrl(e.target.value)}placeholder="https://api.example.com/endpoint"onKeyDown={e=>e.key==="Enter"&&send()}/><button className="send"onClick={send}disabled={loading}>{loading?"Sending…":"Send"}</button></div><textarea className="body" value={requestBody}onChange={e=>setRequestBody(e.target.value)}placeholder='Optional JSON body, e.g. {"name":"Alice"}'/>{apiError&&<div className="alert">{apiError}</div>}{apiResult&&<div className="response"><div className="metrics"><span className={apiResult.status<400?"good":"bad"}>{apiResult.status} {apiResult.statusText}</span><span>{apiResult.duration} ms</span><span>{apiResult.body.length} bytes</span></div><pre>{apiResult.body||"(empty response)"}</pre><details><summary>Response headers</summary><pre>{JSON.stringify(apiResult.headers,null,2)}</pre></details></div>}</>}
{tool==="csv"&&<><label className="drop"><input type="file"accept=".csv,text/csv"onChange={e=>e.target.files?.[0]&&csvFile(e.target.files[0])}/><span className="uploadIcon">↑</span><strong>{csvName||"Choose a CSV file"}</strong><small>Local processing — your file is not uploaded.</small></label>{csvError&&<div className="alert">{csvError}</div>}{rows.length>0&&<><div className="csvbar"><span>{rows.length.toLocaleString()} rows · {columns.length} columns</span><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Filter rows…"/><button onClick={downloadCsv}>Export CSV</button></div><div className="table"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{filtered.slice(0,100).map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{String(r[c]??"")}</td>)}</tr>)}</tbody></table></div><small className="muted">Showing {Math.min(100,filtered.length).toLocaleString()} of {filtered.length.toLocaleString()} matching rows.</small></>}</>}
{tool==="json"&&<div className="json"><div><textarea value={json}onChange={e=>setJson(e.target.value)}spellCheck={false}/>{jsonError&&<div className="alert">{jsonError}</div>}<button className="format"onClick={format}>Format JSON</button></div><pre>{(()=>{try{return JSON.stringify(JSON.parse(json),null,2)}catch{return "Formatted output appears here."}})()}</pre></div>}</section>
<section className="features"><div><b>API testing</b><p>GET, POST, PUT, PATCH and DELETE with status, timing and headers.</p></div><div><b>CSV workflows</b><p>Preview, search and export tabular data locally in your browser.</p></div><div><b>JSON formatting</b><p>Validate and pretty-print JSON without sending it anywhere.</p></div></section></main><footer>API CSV Tools · Free tools for developers</footer></div>}
createRoot(document.getElementById("root")!).render(<App/>);