import{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import Papa from"papaparse";import"./styles.css";
type ApiResult={status:number;statusText:string;duration:number;headers:Record<string,string>;body:string}|null;
type Row=Record<string,unknown>;
type SchemaEntry={path:string;type:string};
type SchemaChange={path:string;kind:"added"|"removed"|"changed"|"same";oldType?:string;newType?:string};
const sample=JSON.stringify({message:"Hello world",ok:true,items:[1,2,3]},null,2);
function schemaType(v:unknown){if(v===null)return"null";if(Array.isArray(v))return"array";return typeof v==="object"?"object":typeof v}
function flattenSchema(value:unknown,path="",out:SchemaEntry[]=[]):SchemaEntry[]{out.push({path:path||"$",type:schemaType(value)});if(value&&typeof value==="object"&&!Array.isArray(value)){for(const[k,v]of Object.entries(value))flattenSchema(v,path?path+"."+k:k,out)}else if(Array.isArray(value)&&value.length){flattenSchema(value[0],path+"[]",out)}return out}
function compareSchemas(oldText:string,newText:string):{changes:SchemaChange[];error:string}{try{const oldJson=JSON.parse(oldText);const newJson=JSON.parse(newText);const oldMap=new Map(flattenSchema(oldJson).map(x=>[x.path,x.type]));const newMap=new Map(flattenSchema(newJson).map(x=>[x.path,x.type]));const paths=[...new Set([...oldMap.keys(),...newMap.keys()])].sort();const changes:SchemaChange[]=paths.map(path=>{const a=oldMap.get(path),b=newMap.get(path);if(a===undefined)return{path,kind:"added",newType:b};if(b===undefined)return{path,kind:"removed",oldType:a};if(a!==b)return{path,kind:"changed",oldType:a,newType:b};return{path,kind:"same",oldType:a,newType:b}});return{changes,error:""}}catch(e){return{changes:[],error:e instanceof Error?e.message:"Invalid JSON"}}}
function App(){const[tool,setTool]=useState<"api"|"csv"|"json"|"schema">("api");const[url,setUrl]=useState("https://jsonplaceholder.typicode.com/todos/1");const[method,setMethod]=useState("GET");const[requestBody,setRequestBody]=useState("");const[apiResult,setApiResult]=useState<ApiResult>(null);const[apiError,setApiError]=useState("");const[loading,setLoading]=useState(false);const[json,setJson]=useState(sample);const[jsonError,setJsonError]=useState("");const[rows,setRows]=useState<Row[]>([]);const[columns,setColumns]=useState<string[]>([]);const[csvName,setCsvName]=useState("");const[csvError,setCsvError]=useState("");const[query,setQuery]=useState("");const[oldSchema,setOldSchema]=useState(JSON.stringify({id:1,name:"John",email:"john@example.com",profile:{active:true}},null,2));const[newSchema,setNewSchema]=useState(JSON.stringify({id:"1",name:"John",phone:"9999999999",profile:{active:true,avatar:"url"}},null,2));const[schemaResult,setSchemaResult]=useState<SchemaChange[]>([]);const[schemaError,setSchemaError]=useState("");
const filtered=useMemo(()=>{if(!query.trim())return rows;const q=query.toLowerCase();return rows.filter(r=>Object.values(r).some(v=>String(v??"").toLowerCase().includes(q)))},[rows,query]);
async function send(){setLoading(true);setApiError("");setApiResult(null);const start=performance.now();try{const r=await fetch(url,{method,headers:{"Content-Type":"application/json","Accept":"application/json,text/plain,*/*"},body:["GET","HEAD"].includes(method)?undefined:(requestBody||undefined)});const text=await r.text();const headers:Record<string,string>={};r.headers.forEach((v,k)=>headers[k]=v);setApiResult({status:r.status,statusText:r.statusText,duration:Math.round(performance.now()-start),headers,body:text})}catch(e){setApiError(e instanceof Error?e.message:"Request failed. Many APIs block browser requests with CORS; use a server-side monitor for those endpoints.")}finally{setLoading(false)}}
function format(){try{setJson(JSON.stringify(JSON.parse(json),null,2));setJsonError("")}catch(e){setJsonError(e instanceof Error?e.message:"Invalid JSON")}}
function csvFile(file:File){setCsvName(file.name);setCsvError("");Papa.parse<Row>(file,{header:true,skipEmptyLines:true,complete:r=>{setRows(r.data);setColumns(r.meta.fields??[])},error:e=>setCsvError(e.message)})}
function downloadBlob(content:string,name:string,type:string){const blob=new Blob([content],{type});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadCsv(){downloadBlob(Papa.unparse(rows),"cleaned-data.csv","text/csv")}
function csvToJson(){try{setJson(JSON.stringify(rows,null,2));setJsonError("");setTool("json")}catch(e){setJsonError(e instanceof Error?e.message:"Could not convert CSV")}}
function jsonToCsv(){try{const value=JSON.parse(json);if(!Array.isArray(value)||!value.every(x=>x&&typeof x==="object"&&!Array.isArray(x)))throw new Error("JSON must be an array of objects.");const csv=Papa.unparse(value as Row[]);downloadBlob(csv,"converted.csv","text/csv");setJsonError("")}catch(e){setJsonError(e instanceof Error?e.message:"Invalid JSON")}}
function cleanCsv(){const cleaned=rows.map(row=>{const out:Row={};for(const key of columns){const normalized=key.trim();if(normalized)out[normalized]=typeof row[key]==="string"?String(row[key]).trim():row[key]}return out});setRows(cleaned);setColumns(columns.map(x=>x.trim()).filter(Boolean))}
function runSchemaDiff(){const r=compareSchemas(oldSchema,newSchema);setSchemaError(r.error);setSchemaResult(r.changes)}
function loadExample(){setOldSchema(JSON.stringify({id:1,name:"John",email:"john@example.com",profile:{active:true}},null,2));setNewSchema(JSON.stringify({id:"1",name:"John",phone:"9999999999",profile:{active:true,avatar:"url"}},null,2));setSchemaError("");setSchemaResult([])}
const added=schemaResult.filter(x=>x.kind==="added"),removed=schemaResult.filter(x=>x.kind==="removed"),changed=schemaResult.filter(x=>x.kind==="changed"),same=schemaResult.filter(x=>x.kind==="same");
return <div className="shell"><header><a className="logo" href="#"><span className="mark">⚡</span> API CSV Tools</a><nav><button className={tool==="api"?"nav active":"nav"} onClick={()=>setTool("api")}>API Tester</button><button className={tool==="csv"?"nav active":"nav"} onClick={()=>setTool("csv")}>CSV Tools</button><button className={tool==="json"?"nav active":"nav"} onClick={()=>setTool("json")}>JSON</button><button className={tool==="schema"?"nav active":"nav"} onClick={()=>setTool("schema")}>Schema Diff</button></nav><a className="github" href="https://github.com/shalubano637-ship-it/api-csv-tools" target="_blank">GitHub ↗</a></header>
<main><section className="hero"><div className="pill">FREE DEVELOPER TOOLKIT</div><h1>Work with APIs and data<br/><em>without the busywork.</em></h1><p>Test HTTP endpoints, compare API schemas, format JSON and inspect CSV files instantly. Your CSV stays in your browser.</p></section>
<section className="toolcard"><div className="tabs"><button className={tool==="api"?"selected":""}onClick={()=>setTool("api")}>API request</button><button className={tool==="csv"?"selected":""}onClick={()=>setTool("csv")}>CSV viewer</button><button className={tool==="json"?"selected":""}onClick={()=>setTool("json")}>JSON formatter</button><button className={tool==="schema"?"selected":""}onClick={()=>setTool("schema")}>Schema diff</button></div>
{tool==="api"&&<><div className="request"><select value={method}onChange={e=>setMethod(e.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input value={url}onChange={e=>setUrl(e.target.value)}placeholder="https://api.example.com/endpoint"onKeyDown={e=>e.key==="Enter"&&send()}/><button className="send"onClick={send}disabled={loading}>{loading?"Sending…":"Send"}</button></div><textarea className="body" value={requestBody}onChange={e=>setRequestBody(e.target.value)}placeholder='Optional JSON body, e.g. {"name":"Alice"}'/>{apiError&&<div className="alert">{apiError}</div>}{apiResult&&<div className="response"><div className="metrics"><span className={apiResult.status<400?"good":"bad"}>{apiResult.status} {apiResult.statusText}</span><span>{apiResult.duration} ms</span><span>{apiResult.body.length} bytes</span></div><pre>{apiResult.body||"(empty response)"}</pre><details><summary>Response headers</summary><pre>{JSON.stringify(apiResult.headers,null,2)}</pre></details></div>}</>}
{tool==="csv"&&<><label className="drop"><input type="file"accept=".csv,text/csv"onChange={e=>e.target.files?.[0]&&csvFile(e.target.files[0])}/><span className="uploadIcon">↑</span><strong>{csvName||"Choose a CSV file"}</strong><small>Local processing — your file is not uploaded.</small></label>{csvError&&<div className="alert">{csvError}</div>}{rows.length>0&&<><div className="csvbar"><span>{rows.length.toLocaleString()} rows · {columns.length} columns</span><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Filter rows…"/><button onClick={cleanCsv}>Clean data</button><button onClick={downloadCsv}>Export CSV</button><button onClick={csvToJson}>CSV → JSON</button></div><div className="table"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{filtered.slice(0,100).map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{String(r[c]??"")}</td>)}</tr>)}</tbody></table></div><small className="muted">Showing {Math.min(100,filtered.length).toLocaleString()} of {filtered.length.toLocaleString()} matching rows.</small></>}</>}
{tool==="json"&&<div className="json"><div><textarea value={json}onChange={e=>setJson(e.target.value)}spellCheck={false}/>{jsonError&&<div className="alert">{jsonError}</div>}<div className="jsonActions"><button className="format"onClick={format}>Format JSON</button><button className="secondary"onClick={jsonToCsv}>JSON → CSV</button></div></div><pre>{(()=>{try{return JSON.stringify(JSON.parse(json),null,2)}catch{return"Formatted output appears here."}})()}</pre></div>}
{tool==="schema"&&<div className="schema"><div className="schemaIntro"><div><b>Compare two JSON responses</b><p>Detect added, removed and type-changed fields by JSON path.</p></div><button className="example"onClick={loadExample}>Load example</button></div><div className="schemaInputs"><div><label>Old response</label><textarea value={oldSchema}onChange={e=>setOldSchema(e.target.value)}spellCheck={false}/></div><div><label>New response</label><textarea value={newSchema}onChange={e=>setNewSchema(e.target.value)}spellCheck={false}/></div></div><button className="diffButton"onClick={runSchemaDiff}>Compare schemas</button>{schemaError&&<div className="alert">{schemaError}</div>}{schemaResult.length>0&&<div className="diffResults"><div className="diffStats"><span className="addedText">+ {added.length} added</span><span className="removedText">− {removed.length} removed</span><span className="changedText">↕ {changed.length} changed</span><span>{same.length} unchanged</span></div>{[...added,...removed,...changed].length===0?<div className="empty">No schema changes detected.</div>:<div className="diffTable">{[...added,...removed,...changed].map((x,i)=><div className="diffRow"key={x.path+i}><code>{x.path}</code><span className={"kind "+x.kind}>{x.kind}</span><span className="types">{x.oldType&&<>{x.oldType}</>}{x.oldType&&x.newType&&" → "}{x.newType&&<>{x.newType}</>}</span></div>)}</div>}</div>}</div>}
</section><section className="features"><div><b>API testing</b><p>GET, POST, PUT, PATCH and DELETE with status, timing and headers.</p></div><div><b>Schema diff</b><p>Compare JSON responses and find added, removed and type-changed fields.</p></div><div><b>CSV workflows</b><p>Clean, search, convert and export CSV data locally in your browser.</p></div></section></main><footer>API CSV Tools · Free tools for developers</footer></div>}
createRoot(document.getElementById("root")!).render(<App/>);